import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';import {createRequire} from 'node:module';import {fixture} from './fixtures.mjs';
import '../assets/starter/model.js';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),root=path.resolve(import.meta.dirname,'..'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'handbook-full-'));
const artifacts=path.resolve(process.env.HANDBOOK_ARTIFACTS||path.join(tmp,'screenshots'));fs.mkdirSync(artifacts,{recursive:true});
const sets={};for(const kind of ['solo','pair','group']){const data=fixture(kind);if(kind==='pair'){data.trip.title='一段有长标题的完整旅行手册';data.people[0].displayName='旅伴名字较长';data.flights.push({id:'return',code:'SAMPLE2',departureAt:'2027-04-20T14:00:00+09:00',arrivalAt:'2027-04-20T16:00:00+08:00',origin:{city:'京都',timeZone:'Asia/Tokyo'},destination:{city:'上海',timeZone:'Asia/Shanghai'},status:'proposed'});}data.budget.defaultCurrency='CNY';data.days[0].events.push({id:'timed',time:'10:00–11:00',title:'预约参观',endTime:'11:00'});data.stays[0].room='双床房';data.stays[0].breakfast='含早餐';data.stays[0].requirements='22点前入住';data.stays[0].price={amount:1200,currency:'CNY',members:data.people.map(p=>p.id)};const coords=kind==='solo'?{latitude:30.27,longitude:120.15}:kind==='pair'?{latitude:35.01,longitude:135.77}:{latitude:-33.87,longitude:151.21};for(const d of data.days){d.coordinates=coords;d.route=[{name:d.city,...coords},{name:'周边目的地',latitude:coords.latitude+.3,longitude:coords.longitude+.3}];}const file=path.join(tmp,kind+'.json'),out=path.join(tmp,kind);fs.writeFileSync(file,JSON.stringify(data));const r=spawnSync(process.execPath,[path.join(root,'scripts/create-handbook.mjs'),file,out,'local'],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);sets[kind]={data:JSON.parse(fs.readFileSync(path.join(out,'trip-data.json'),'utf8')),out,state:globalThis.HandbookModel.emptyState(data)};}
{const data=fixture('solo');data.trip.id='test-modules';data.modules={today:false,trip:true,budget:true,prepare:false};const file=path.join(tmp,'modules.json'),out=path.join(tmp,'modules');fs.writeFileSync(file,JSON.stringify(data));const r=spawnSync(process.execPath,[path.join(root,'scripts/create-handbook.mjs'),file,out,'local'],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);sets.modules={data:JSON.parse(fs.readFileSync(path.join(out,'trip-data.json'),'utf8')),out,state:globalThis.HandbookModel.emptyState(data)};}
// Synthetic regression case: arrival-only flight and dense, multi-day local routes.
{const data=fixture('solo');data.trip.id='sparse-dense';data.days[0].events=[{id:'lunch',time:'13:00',title:'午餐'},{id:'evening',time:'20:00',title:'晚间安排'}];data.flights=[{id:'arrival-only',date:'2027-04-18',arrivalAt:'2027-04-18T12:30:00+08:00',origin:{city:'出发地待补'},destination:{city:'杭州',timeZone:'Asia/Shanghai'},status:'proposed'}];data.days.forEach((d,i)=>{d.coordinates={latitude:30.27+i*.2,longitude:120.15+i*.2};d.route=Array.from({length:10},(_,j)=>({name:'测试地点'+i+'-'+j,latitude:d.coordinates.latitude+j*.002,longitude:d.coordinates.longitude+j*.002}));});const file=path.join(tmp,'sparse.json'),out=path.join(tmp,'sparse');fs.writeFileSync(file,JSON.stringify(data));const r=spawnSync(process.execPath,[path.join(root,'scripts/create-handbook.mjs'),file,out,'local'],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);sets.sparse={data:JSON.parse(fs.readFileSync(path.join(out,'trip-data.json'))),out,state:HandbookModel.emptyState(data)};}
// Public synthetic Japan case: 100 attractions must remain three city markers.
{const data=fixture('solo');data.trip={...data.trip,id:'japan-map-regression',title:'东京 · 镰仓 · 箱根',countries:['JP']};data.days=[['东京',139.69,35.68],['镰仓',139.55,35.32],['箱根',139.1,35.23]].map(([city,longitude,latitude],i)=>({date:'2027-04-'+(18+i),city,countryCode:'JP',coordinates:{longitude,latitude},events:[],route:Array.from({length:34},(_,j)=>({name:'景点'+i+'-'+j,longitude:longitude+j*.001,latitude}))}));data.flights=[{id:'example-arrival',date:'2027-04-18',origin:{city:'上海',countryCode:'CN'},destination:{city:'东京',countryCode:'JP'},status:'proposed'}];const file=path.join(tmp,'japan.json'),out=path.join(tmp,'japan');fs.writeFileSync(file,JSON.stringify(data));const r=spawnSync(process.execPath,[path.join(root,'scripts/create-handbook.mjs'),file,out,'local'],{encoding:'utf8'});assert.equal(r.status,0,r.stderr);sets.japan={data:JSON.parse(fs.readFileSync(path.join(out,'trip-data.json'))),out,state:HandbookModel.emptyState(data)};}
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png'},server=http.createServer(async(req,res)=>{const [kind,...parts]=new URL(req.url,'http://local').pathname.slice(1).split('/'),s=sets[kind];if(!s){res.writeHead(404);res.end();return;}const file=parts.join('/')||'index.html';if(file==='config.js'){res.setHeader('Content-Type','text/javascript');res.end('window.HANDBOOK_CONFIG={storage:"cloud"}');return;}if(file==='api/state'){if(req.method==='POST'){let raw='';for await(const c of req)raw+=c;try{s.state=HandbookModel.applyOperation(s.state,JSON.parse(raw),s.data);}catch(e){res.writeHead(e.status||400,{'Content-Type':'application/json'});res.end(JSON.stringify({error:e.message}));return;}}res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify({state:s.state}));return;}const absolute=path.resolve(s.out,'public',file);if(!absolute.startsWith(path.join(s.out,'public')+path.sep)||!fs.existsSync(absolute)){res.writeHead(404);res.end();return;}res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream'});res.end(fs.readFileSync(absolute));});
await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome'}),errors=[];
try{const base=`http://127.0.0.1:${server.address().port}`;for(const kind of ['solo','pair','group']){
 const p=await browser.newPage({viewport:{width:390,height:844}});p.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message);});await p.route('https://api.open-meteo.com/**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({current:{temperature_2m:23,apparent_temperature:22,weather_code:2,wind_speed_10m:10},daily:{time:['2027-04-18','2027-04-19'],temperature_2m_min:[15,17],temperature_2m_max:[24,26],weather_code:[2,3],uv_index_max:[5,6],precipitation_probability_max:[10,20],wind_speed_10m_max:[12,14]}})}));await p.goto(base+'/'+kind+'/?previewNow=2027-04-18T12:00:00%2B09:00');await p.waitForSelector('#main > *');
 for(const tab of ['today','trip','budget','prepare']){await p.click(`[data-page=${tab}]`);await p.waitForFunction(id=>document.querySelector('[data-page="'+id+'"]').classList.contains('active'),tab);await p.screenshot({path:path.join(artifacts,kind+'-'+tab+'.png'),fullPage:true});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,kind+' '+tab+' overflow');await p.setViewportSize({width:320,height:740});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,kind+' '+tab+' 320 overflow');assert.equal(await p.evaluate(()=>{const title=document.querySelector('.greeting span').getBoundingClientRect(),member=document.querySelector('.member-entry').getBoundingClientRect();return title.right<=member.left;}),true,kind+' header overlap');await p.setViewportSize({width:390,height:844});}
 assert.equal(await p.locator('.clothing-guide').count(),1);await p.click('[data-page=budget]');assert.equal(await p.locator('.budget-donut').count(),0);assert.equal(await p.locator('[data-expense-add]').count(),1);await p.locator('[data-hotel]').first().click();assert.match(await p.locator('#modal-body').innerText(),/双床房[\s\S]*含早餐[\s\S]*22点前入住/);await p.click('#close');
 await p.click('[data-page=trip]');await p.locator('[data-day="1"]').click();assert((await p.locator('.world-land').count())>=1);assert.equal(await p.locator('.timeline .map-link').count(),1);assert.equal(await p.getByText('留一点余地').count(),0);
 if(kind==='group'){
  await p.click('[data-page=prepare]');const input=p.locator('[data-add-pack=essentials] input');await input.fill('雨天备用袜子');const node=await input.elementHandle();await p.evaluate(()=>dispatchEvent(new Event('handbookchange')));await p.waitForTimeout(1200);assert.equal(await node.evaluate(el=>el===document.activeElement&&el.isConnected),true);await p.locator('[data-add-pack=essentials] button').click();await p.waitForFunction(()=>HandbookStore.get().personal.length===1);assert.equal(await input.inputValue(),'');await p.click('[data-remove-pack=passport]');await p.waitForFunction(()=>HandbookStore.get().checks.some(c=>c.itemId==='hidden:passport'));assert.equal(await p.locator('[data-remove-pack=passport]').count(),0);
  const q=await browser.newPage({viewport:{width:390,height:844}});q.on('pageerror',e=>errors.push(e.message));await q.goto(base+'/group/');await q.click('#member-entry');await q.click('[data-member=member-2]');await q.click('[data-page=prepare]');await q.click('#copy-list');await q.click('[data-copy-person=member-1]');await q.waitForFunction(()=>HandbookStore.get().personal.length===2);assert.equal(await q.locator('[data-remove-pack=passport]').count(),1);assert.notEqual(sets.group.state.personal[0].id,sets.group.state.personal[1].id);
  await q.click('[data-page=budget]');for(const amount of ['747,50','12.345','.50']){await q.click('[data-expense-add]');await q.click('[data-currency=CNY]');await q.fill('[name=amount]',amount);await q.fill('[name=purpose]','测试晚餐');await q.click('.expense-save');await q.waitForSelector('.expense-form',{state:'detached'});}assert.deepEqual(sets.group.state.expenses.map(e=>e.cents),[74750,1235,50]);assert.equal(await q.locator('.budget-donut').count(),1);
  await q.locator('.expense-notice button').click();await q.waitForFunction(()=>HandbookStore.get().expenses.length===2);assert.equal(sets.group.state.expenses.length,2);
  await q.click('[data-expense-add]');await q.fill('[name=purpose]','三人均摊');await q.fill('[name=amount]','1');await q.locator('[name=member][value=member-1]').check();await q.locator('[name=member][value=member-3]').check();await q.click('.expense-save');await q.waitForSelector('.expense-form',{state:'detached'});assert.equal(sets.group.state.expenses.at(-1).members.length,3);
  for(let i=0;i<7;i++){await q.click('[data-expense-add]');await q.fill('[name=purpose]','待支付'+i);await q.fill('[name=amount]','10');await q.check('[name=paymentStatus][value=unpaid]');await q.click('.expense-save');await q.waitForSelector('.expense-form',{state:'detached'});}assert.equal(await q.locator('.expense-pending [data-expense-edit]:visible').count(),5);await q.locator('.expense-pending summary').click();assert.equal(await q.locator('.expense-pending [data-expense-edit]:visible').count(),7);
  await q.locator('.expense-pending [data-swipe-action=pay]').first().focus();await q.keyboard.press('Enter');await q.waitForFunction(()=>HandbookStore.get().expenses.filter(e=>e.status==='pending').length===6);await q.locator('.expense-notice button').click();await q.waitForFunction(()=>HandbookStore.get().expenses.filter(e=>e.status==='pending').length===7);
  const swipeRow=q.locator('.expense-pending [data-swipe-action=pay]').first();await swipeRow.scrollIntoViewIfNeeded();const box=await swipeRow.boundingBox();await q.mouse.move(box.x+box.width*.95,box.y+box.height/2);await q.mouse.down();await q.mouse.move(box.x+box.width*.05,box.y+box.height/2,{steps:12});await q.mouse.up();await q.waitForFunction(()=>HandbookStore.get().expenses.filter(e=>e.status==='pending').length===6);await q.locator('.expense-notice button').click();await q.waitForFunction(()=>HandbookStore.get().expenses.filter(e=>e.status==='pending').length===7);
  await q.click('[data-expense-all]');await q.click('[data-filter=餐饮]');assert.equal(await q.locator('.expense-all-rows [data-expense-edit]').count(),3);await q.locator('.expense-all .expense-close').click();await q.reload();await q.waitForSelector('.expense-pending');assert.equal(sets.group.state.expenses.length,10);await q.close();
  await p.reload();await p.click('[data-page=budget]');await p.waitForSelector('[data-swipe-action=settle]');await p.locator('[data-swipe-action=settle]').first().focus();await p.keyboard.press('Enter');await p.waitForFunction(()=>HandbookStore.get().settlements.length===1);await p.locator('.expense-notice button').click();await p.waitForFunction(()=>HandbookStore.get().settlements.length===0);
  await p.click('[data-expense-add]');await p.fill('[name=amount]','23.45');await p.screenshot({path:path.join(artifacts,'full-expense-form.png'),fullPage:true});await p.setViewportSize({width:320,height:740});assert.equal(await p.locator('.expense-sheet').evaluate(el=>el.scrollWidth<=el.clientWidth+1),true);await p.click('.expense-close');await p.setViewportSize({width:390,height:844});
  await p.click('[data-page=prepare]');assert.equal(await p.locator('#save-offline').count(),0);

 }
 await p.close();
}
 const jp=await browser.newPage({viewport:{width:390,height:844}});jp.on('pageerror',e=>errors.push(e.message));await jp.goto(base+'/japan/#trip');await jp.waitForSelector('[data-map-level=city]');assert.equal(await jp.locator('[data-map-level=city] [data-map-point]').count(),3);assert.equal(await jp.locator('[data-map-level=country] [data-map-point]').count(),2);assert.equal(await jp.locator('[data-map-level=city] [data-map-label]').count(),3);await jp.locator('section[aria-label="城市路线"]').screenshot({path:path.join(artifacts,'japan-city-map.png')});await jp.locator('[aria-label="世界路线"]').first().screenshot({path:path.join(artifacts,'japan-world-map.png')});await jp.close();
 const sparse=await browser.newPage({viewport:{width:390,height:844}});sparse.on('pageerror',e=>errors.push(e.message));await sparse.goto(base+'/sparse/?previewNow='+encodeURIComponent('2027-04-17T08:00:00+08:00'));await sparse.waitForSelector('.activity-focus');assert.equal(await sparse.locator('.trip-overview').count(),0);await sparse.screenshot({path:path.join(artifacts,'sparse-before-trip.png'),fullPage:true});await sparse.click('[data-page=trip]');const text=await sparse.locator('.timeline').innerText();assert(text.indexOf('12:30')<text.indexOf('13:00'));assert.equal(await sparse.locator('.timeline .flight-card').count(),0);assert.equal(await sparse.locator('[data-map-point]').count(),1);const boxes=await sparse.locator('[data-map-label]').evaluateAll(nodes=>nodes.map(n=>{const r=n.getBBox();return {x:r.x,y:r.y,w:r.width,h:r.height};}));for(let i=0;i<boxes.length;i++){const a=boxes[i];assert(a.x>=0&&a.y>=0&&a.x+a.w<=570&&a.y+a.h<=300);for(const b of boxes.slice(i+1))assert(!(a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y));}await sparse.screenshot({path:path.join(artifacts,'sparse-timeline-map.png'),fullPage:true});await sparse.click('[data-page=prepare]');assert.equal(await sparse.locator('#save-offline').count(),0);await sparse.close();
 const modules=await browser.newPage({viewport:{width:390,height:844}});await modules.goto(base+'/modules/#today');await modules.waitForSelector('#main > *');assert.equal(await modules.locator('[data-page=today]:visible').count(),0);assert.equal(await modules.locator('[data-page=prepare]:visible').count(),0);assert.equal(await modules.locator('[data-page=trip].active').count(),1);await modules.click('[data-page=budget]');assert.equal(await modules.locator('[data-expense-add]').count(),1);await modules.close();
 const flight=await browser.newPage({viewport:{width:390,height:844}});flight.on('pageerror',e=>errors.push(e.message));
 for(const [time,expected] of [['2027-04-17T10:00:00+08:00','距离下一程起飞'],['2027-04-18T01:00:00+08:00','航班号待补']]){await flight.goto(base+'/pair/?previewNow='+encodeURIComponent(time));await flight.waitForSelector('.flight-card');assert((await flight.locator('#main').innerText()).includes(expected));await flight.screenshot({path:path.join(artifacts,expected==='距离下一程起飞'?'before-flight.png':'during-flight.png'),fullPage:true});}
 await flight.goto(base+'/pair/?previewNow='+encodeURIComponent('2027-04-18T01:00:00+08:00'));await flight.waitForSelector('.in-flight');await flight.waitForTimeout(1500);assert.match(await flight.locator('.in-flight .moment-title').innerText(),/飞行中.*距离抵达/);assert.equal((await flight.locator('.in-flight .moment-count').innerText()).replace(/\s/g,''),'5小时0分');assert.doesNotMatch(await flight.locator('.in-flight').innerText(),/SAMPLE2|距离下一程起飞/);await flight.close();assert.deepEqual(errors,[]);console.log('PASS full UI: 3 trips x 4 tabs, 320/390, map, hotel details, chart, original expense form, decimal rounding, undo, split, pending folding/payment undo, filters, shared checklist/copy/focus. '+artifacts);
}finally{await browser.close();server.close();}
