#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createHash} from 'node:crypto';
import {fixture} from '../tests/fixtures.mjs';
const root=path.dirname(path.dirname(fileURLToPath(import.meta.url))),destination=path.resolve(process.argv[2]||'release'),folder=path.join(destination,'triploom-handbook');
if(fs.existsSync(folder))throw Error('Use a fresh release directory');
const files=['SKILL.md','README.md','agents/openai.yaml','references/intake.md','references/data-model.md','references/product-contract.md','references/deployment.md','references/verification.md','assets/country-currencies.json','assets/starter/index.html','assets/starter/styles.css','assets/starter/model.js','assets/starter/store.js','assets/starter/engine.js','assets/starter/weather.js','assets/starter/illustrations/default-journey.svg','assets/server/core.mjs','assets/server/cloudbase.cjs','assets/server/cloudflare.mjs','assets/server/postgres.sql','assets/server/d1.sql','assets/default-avatars/manifest.json',...Array.from({length:4},(_,i)=>'assets/default-avatars/portrait-'+(i+1)+'.webp'),'scripts/create-handbook.mjs','scripts/validate-trip-data.mjs','scripts/cloudbase-seed.mjs','scripts/stage-cloudbase.mjs','scripts/package-skill.mjs','tests/fixtures.mjs','tests/model.test.mjs','tests/integration.test.mjs','tests/browser.mjs','tests/postgres.mjs','tests/cloudflare-runtime.mjs'];
for(const file of ['assets/starter/index.html','assets/starter/styles.css','assets/starter/engine.js','assets/starter/weather.js','tests/browser.mjs'])files.splice(files.indexOf(file),1);
files.push('references/decisions.md','references/source-review.md','references/acceptance.md','references/conversation-contract.md','references/map-system.md','scripts/check-intake.mjs','scripts/verify-project.mjs','scripts/serve-handbook.mjs','tests/intake.test.mjs','tests/maps.test.mjs','scripts/extract-xlsx.py','tests/documents.test.mjs','tests/store.test.mjs','tests/full-browser.mjs','assets/default-preparation.json','references/full-feature-contract.md',...fs.readdirSync(path.join(root,'assets/full')).map(f=>'assets/full/'+f));
const hashes={};let bytes=0;
for(const name of files){const content=fs.readFileSync(path.join(root,name));const text=content.toString('utf8');if(/\/Users\/|\.service\.tcloudbase\.com/i.test(text))throw Error('Private reference in '+name);const target=path.join(folder,name);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,content);hashes[name]=createHash('sha256').update(content).digest('hex');bytes+=content.length;}
const example=fixture('pair');example.trip.id='example-trip';example.trip.title='示例旅行（请替换全部资料）';const exampleBytes=JSON.stringify(example,null,2);fs.writeFileSync(path.join(folder,'assets/trip-data.example.json'),exampleBytes);hashes['assets/trip-data.example.json']=createHash('sha256').update(exampleBytes).digest('hex');
fs.writeFileSync(path.join(folder,'release.json'),JSON.stringify({version:'3.1.0',schemaVersion:1,files:hashes},null,2));
console.log(JSON.stringify({folder,files:files.length+2,bytes},null,2));
